import { expect, test } from '@playwright/test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import sharp from 'sharp';
import { startServer } from './server.ts';
import type { AnswerPageList, Question } from '../../src/shared/collection.ts';

test('学习端先无答案收集，再补同页和另页解答，其他小题复用答案页且解除首题不影响原图', async ({ page, request }) => {
  const dir = await mkdtemp(join(tmpdir(), 'klbook-answers-'));
  const server = await startServer(dir);
  try {
    const setupCode = (await readFile(join(dir, 'setup-code.txt'), 'utf8')).trim();
    const first = await (await request.post(`${server.url}/api/v1/setup`, { data: { setupCode, username: 'parent', password: 'family password 123', learnerName: '小明', deviceName: '设置电脑' } })).json();
    const headers = { Authorization: `Bearer ${first.token}` };
    const bytes = await sharp(await readFile('test/fixtures/paper.svg')).png().toBuffer();
    const paper = await (await request.post(`${server.url}/api/v1/collection/pages`, { headers: { ...headers, 'Content-Type': 'image/png', 'Idempotency-Key': crypto.randomUUID() }, data: bytes })).json();
    const question: Question = await (await request.post(`${server.url}/api/v1/collection/pages/${paper.id}/questions`, { headers, data: { operationId: crypto.randomUUID(), state: 'collected', subjectId: 'math', region: { x: 0, y: 0, width: 1, height: .4 }, sourceId: null, pageNumber: '', questionNumber: '1', note: '' } })).json();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`${server.url}/learn`);
    await page.getByLabel('家长账号').fill('parent'); await page.getByLabel('家长密码', { exact: true }).fill('family password 123');
    await page.getByRole('button', { name: '登录此设备', exact: true }).click();
    await page.getByRole('button', { name: '打开错题', exact: true }).click();
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    await expect(page.getByLabel('拍摄答案', { exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '从本题原始页 1 框选', exact: true }).click();
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('heading', { name: '错题详情', exact: true })).toBeVisible();
    await page.getByText('查看纸质答案（1 个解答区）', { exact: true }).click();
    await expect(page.getByRole('img', { name: '纸质解答区', exact: true })).toHaveCount(1);
    await page.getByRole('button', { name: '整理纸质答案', exact: true }).click();
    await expect(page.getByLabel('选择答案图片', { exact: true })).toBeEnabled();
    const continuation = await sharp(bytes).flop().png().toBuffer();
    await page.getByLabel('选择答案图片', { exact: true }).setInputFiles({ name: '答案续页.png', mimeType: 'image/png', buffer: continuation });
    await expect(page.getByRole('button', { name: '解答区 2', exact: true })).toHaveAttribute('aria-pressed', 'true');
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.getByRole('button', { name: '向前移动', exact: true }).click();
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await page.getByRole('button', { name: '查看原始页', exact: true }).click();
    await expect(page.getByRole('img', { name: '原始页（保留作答和批改）', exact: true })).toHaveCount(2);
    const saved: Question = await (await request.get(`${server.url}/api/v1/collection/questions/${question.id}`, { headers })).json();
    expect(saved.collectedAt).toBe(question.collectedAt); expect(saved.parts).toEqual(question.parts);
    await page.getByRole('button', { name: '从此原始页再收集一道', exact: true }).click();
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.getByRole('button', { name: '下一步，选学科', exact: true }).click();
    await page.getByRole('combobox', { name: '学科', exact: true }).selectOption('math'); await page.getByLabel('题号（选填）').fill('2');
    await page.getByRole('button', { name: '保存到错题集', exact: true }).click();
    await expect(page.getByText('查看纸质答案（2 个解答区）', { exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '从已有答案页选择', exact: true }).click();
    const choices: AnswerPageList = await (await request.get(`${server.url}/api/v1/collection/answer-pages`, { headers })).json();
    const index = choices.items.findIndex(item => item.id === saved.answerParts[0]!.originalPage.id);
    await page.getByRole('button', { name: `使用答案页 ${index + 1}`, exact: true }).click();
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await page.getByRole('button', { name: '返回列表', exact: true }).click();
    await page.getByRole('article').filter({ has: page.getByRole('heading', { name: '未填写来源 · 第 1 题', exact: true }) }).getByRole('button', { name: '打开错题', exact: true }).click();
    await page.getByRole('button', { name: '整理纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '移除此解答区', exact: true }).click(); await page.getByRole('button', { name: '移除此解答区', exact: true }).click();
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('button', { name: '补充纸质答案', exact: true })).toBeVisible();
    await page.reload();
    await page.getByRole('article').filter({ has: page.getByRole('heading', { name: '未填写来源 · 第 2 题', exact: true }) }).getByRole('button', { name: '打开错题', exact: true }).click();
    await page.getByText('查看纸质答案（1 个解答区）', { exact: true }).click();
    await expect(page.getByRole('img', { name: '纸质解答区', exact: true })).toHaveCount(1);
    expect(await (await request.get(`${server.url}/api/v1/collection/pages/${saved.answerParts[0]!.originalPage.id}/original`, { headers })).body()).toEqual(continuation);
    for (const width of [390, 820, 1440]) { await page.setViewportSize({ width, height: 844 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: `test-results/answers-${width}-${test.info().project.name}.png`, fullPage: true }); }
  } finally { await server.stop(); await rm(dir, { recursive: true, force: true }); }
});

test('后台后补答案保护未保存修改，上传和保存响应丢失可恢复，权限与并发冲突保留解答区', async ({ page, request }) => {
  const dir = await mkdtemp(join(tmpdir(), 'klbook-answer-retry-'));
  const server = await startServer(dir);
  try {
    const setupCode = (await readFile(join(dir, 'setup-code.txt'), 'utf8')).trim();
    const first = await (await request.post(`${server.url}/api/v1/setup`, { data: { setupCode, username: 'parent', password: 'family password 123', learnerName: '小明', deviceName: '设置电脑' } })).json();
    const headers = { Authorization: `Bearer ${first.token}` };
    const bytes = await sharp(await readFile('test/fixtures/paper.svg')).png().toBuffer();
    const paper = await (await request.post(`${server.url}/api/v1/collection/pages`, { headers: { ...headers, 'Content-Type': 'image/png', 'Idempotency-Key': crypto.randomUUID() }, data: bytes })).json();
    const question: Question = await (await request.post(`${server.url}/api/v1/collection/pages/${paper.id}/questions`, { headers, data: { operationId: crypto.randomUUID(), state: 'collected', subjectId: 'math', region: { x: 0, y: 0, width: 1, height: .4 }, sourceId: null, pageNumber: '', questionNumber: '1', note: '' } })).json();
    const answerUrl = `${server.url}/api/v1/collection/questions/${question.id}/answers`;
    await page.goto(`${server.url}/admin/materials`);
    await page.getByLabel('家长账号').fill('parent'); await page.getByLabel('家长密码', { exact: true }).fill('family password 123');
    await page.getByRole('button', { name: '登录此设备', exact: true }).click();
    await page.getByLabel('家长密码', { exact: true }).fill('family password 123'); await page.getByRole('button', { name: '验证并进入管理', exact: true }).click();
    await page.getByRole('table', { name: '已收集资料' }).getByRole('button', { name: '打开', exact: true }).click();
    let resumeRead!: () => void;
    const pausedRead = new Promise<void>(resolve => { resumeRead = resolve; });
    await page.route(`${server.url}/api/v1/collection/questions/${question.id}`, async route => { await pausedRead; await route.continue(); }, { times: 1 });
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    try { await expect(page.getByLabel('备注（选填）')).toBeDisabled(); } finally { resumeRead(); }
    await expect(page.getByRole('heading', { name: '整理纸质答案', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '返回题目', exact: true }).click();
    await page.getByLabel('备注（选填）').fill('先保护本题的备注');
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '保存后离开', exact: true }).click();
    await expect(page.getByRole('heading', { name: '整理纸质答案', exact: true })).toBeVisible();
    await page.route('**/api/v1/collection/pages', async route => { await route.fetch({ postData: bytes }); await route.abort(); }, { times: 1 });
    await expect(page.getByLabel('选择答案图片', { exact: true })).toBeEnabled();
    await page.getByLabel('选择答案图片', { exact: true }).setInputFiles({ name: '后补答案.png', mimeType: 'image/png', buffer: bytes });
    await expect(page.getByRole('alert')).toContainText('仍保留');
    await page.reload();
    await page.getByLabel('家长密码', { exact: true }).fill('family password 123'); await page.getByRole('button', { name: '验证并进入管理', exact: true }).click();
    await page.getByRole('table', { name: '已收集资料' }).getByRole('button', { name: '打开', exact: true }).click();
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '继续追加 后补答案.png', exact: true }).click();
    await page.getByRole('button', { name: '返回题目', exact: true }).click();
    await page.getByRole('button', { name: '保存后离开', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('请先框选每个解答区');
    await page.getByRole('button', { name: '继续编辑', exact: true }).click();
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.route(answerUrl, async route => { await route.fetch(); await route.abort(); }, { times: 1 });
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('仍保留');
    await page.getByText('精确调整范围（百分比）', { exact: true }).click(); await page.getByLabel('范围高度', { exact: true }).fill('50');
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByLabel('备注（选填）')).toHaveValue('先保护本题的备注');
    let saved: Question = await (await request.get(`${server.url}/api/v1/collection/questions/${question.id}`, { headers })).json();
    expect(saved.answerParts).toHaveLength(1); expect(saved.answerParts[0]!.region!.height).toBe(.5);
    expect(saved.collectedAt).toBe(question.collectedAt);
    await page.getByRole('button', { name: '整理纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '在本页补充解答区', exact: true }).click(); await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await request.put(answerUrl, { headers, data: { operationId: crypto.randomUUID(), expectedRevision: saved.revision, parts: [] } });
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('其他页面更新');
    await expect(page.getByRole('button', { name: '解答区 2', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '返回题目', exact: true }).click(); await page.getByRole('button', { name: '放弃本次修改并离开', exact: true }).click();
    await page.getByRole('button', { name: '返回列表', exact: true }).click();
    await page.getByRole('table', { name: '已收集资料' }).getByRole('button', { name: '打开', exact: true }).click();
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '从本题原始页 1 框选', exact: true }).click(); await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.route(answerUrl, async route => {
      const sent = route.request().headers();
      await request.delete(`${server.url}/api/v1/admin/grants`, { headers: { Authorization: sent.authorization!, 'X-Parent-Authorization': sent['x-parent-authorization']! } });
      await route.continue();
    }, { times: 1 });
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('heading', { name: '验证家长身份', exact: true })).toBeVisible();
    await page.getByLabel('家长密码', { exact: true }).fill('family password 123'); await page.getByRole('button', { name: '验证并进入管理', exact: true }).click();
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByLabel('备注（选填）')).toHaveValue('先保护本题的备注');
    saved = await (await request.get(`${server.url}/api/v1/collection/questions/${question.id}`, { headers })).json();
    expect(saved.answerParts).toHaveLength(1); expect(saved.answerParts[0]!.originalPage.id).toBe(paper.id);
  } finally { await server.stop(); await rm(dir, { recursive: true, force: true }); }
});
