import { expect, test } from '@playwright/test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import sharp from 'sharp';
import { startServer } from './server.ts';

test('两个独立登录页面核对双方修改，保留本次编辑后再次冲突仍保护输入，最终保存重开不重复', async ({ page, browser, request }) => {
  const dir = await mkdtemp(join(tmpdir(), 'klbook-conflicts-'));
  const server = await startServer(dir);
  const other = await browser.newContext({ viewport: { width: 390, height: 844 } });
  try {
    const setupCode = (await readFile(join(dir, 'setup-code.txt'), 'utf8')).trim();
    const first = await (await request.post(`${server.url}/api/v1/setup`, { data: { setupCode, username: 'parent', password: 'family password 123', learnerName: '小明', deviceName: '设置电脑' } })).json();
    const headers = { Authorization: `Bearer ${first.token}` };
    const bytes = await sharp(await readFile('test/fixtures/paper.svg')).png().toBuffer();
    const draft = await (await request.post(`${server.url}/api/v1/collection/drafts`, { headers: { ...headers, 'Content-Type': 'image/png', 'Idempotency-Key': crypto.randomUUID() }, data: bytes })).json();
    const url = `${server.url}/api/v1/collection/questions/${draft.id}`;
    const input = { operationId: crypto.randomUUID(), expectedRevision: 1, state: 'collected', subjectId: 'math', region: { x: 0, y: 0, width: 1, height: 1 }, sourceId: null, pageNumber: '', questionNumber: '1', note: '' };
    expect((await request.put(url, { headers, data: input })).ok()).toBeTruthy();
    const phone = await other.newPage();
    for (const device of [page, phone]) {
      await device.goto(`${server.url}/learn`);
      await device.getByLabel('家长账号').fill('parent'); await device.getByLabel('家长密码', { exact: true }).fill('family password 123');
      await device.getByRole('button', { name: '登录此设备', exact: true }).click();
      await device.getByRole('button', { name: '打开错题', exact: true }).click();
      await device.getByRole('button', { name: '补充或更正信息', exact: true }).click();
    }
    await page.getByLabel('备注（选填）').fill('电脑补充的解题观察');
    await phone.getByLabel('备注（选填）').fill('手机上还没保存的想法');
    await page.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(page.getByRole('heading', { name: '错题详情', exact: true })).toBeVisible();
    await phone.getByRole('button', { name: '保存修改', exact: true }).click();
    const conflict = phone.getByRole('region', { name: '处理保存冲突', exact: true });
    await expect(conflict).toBeVisible();
    await expect(conflict.getByRole('region', { name: '当前版本', exact: true })).toContainText('电脑补充的解题观察');
    await expect(conflict.getByRole('region', { name: '本次编辑', exact: true })).toContainText('手机上还没保存的想法');
    await expect(phone.getByLabel('备注（选填）')).toHaveValue('手机上还没保存的想法');
    await phone.screenshot({ path: 'test-results/question-conflict-390.png', fullPage: true });
    expect(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await conflict.getByRole('button', { name: '保留本次编辑，继续核对', exact: true }).click();
    await phone.getByLabel('备注（选填）').fill('电脑和手机核对后的完整记录');
    expect((await request.put(url, { headers, data: { ...input, operationId: crypto.randomUUID(), expectedRevision: 3, note: '核对期间电脑又有更新' } })).ok()).toBeTruthy();
    await phone.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(conflict.getByRole('region', { name: '当前版本', exact: true })).toContainText('核对期间电脑又有更新');
    await expect(phone.getByLabel('备注（选填）')).toHaveValue('电脑和手机核对后的完整记录');
    await conflict.getByRole('button', { name: '保留本次编辑，继续核对', exact: true }).click();
    await phone.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(phone.getByRole('heading', { name: '错题详情', exact: true })).toBeVisible();
    await page.reload(); await page.getByRole('button', { name: '打开错题', exact: true }).click();
    await expect(page.getByText('电脑和手机核对后的完整记录', { exact: true })).toBeVisible();
    const saved = await (await request.get(url, { headers })).json();
    expect(saved.revision).toBe(5);
    expect((await (await request.get(`${server.url}/api/v1/collection/questions?state=collected`, { headers })).json()).total).toBe(1);
  } finally { await other.close(); await server.stop(); await rm(dir, { recursive: true, force: true }); }
});

test('后台保存回执丢失后遇到更新不虚报成功，核对读取失败和家长验证失效均保留编辑与跨页材料', async ({ page, request }) => {
  const dir = await mkdtemp(join(tmpdir(), 'klbook-conflict-retry-'));
  const server = await startServer(dir);
  try {
    const setupCode = (await readFile(join(dir, 'setup-code.txt'), 'utf8')).trim();
    const first = await (await request.post(`${server.url}/api/v1/setup`, { data: { setupCode, username: 'parent', password: 'family password 123', learnerName: '小明', deviceName: '另一设备' } })).json();
    const headers = { Authorization: `Bearer ${first.token}` };
    const bytes = await sharp(await readFile('test/fixtures/paper.svg')).png().toBuffer();
    const draft = await (await request.post(`${server.url}/api/v1/collection/drafts`, { headers: { ...headers, 'Content-Type': 'image/png', 'Idempotency-Key': crypto.randomUUID() }, data: bytes })).json();
    const url = `${server.url}/api/v1/collection/questions/${draft.id}`;
    const fields = { state: 'collected', subjectId: 'math', region: { x: 0, y: 0, width: 1, height: 1 }, sourceId: null, pageNumber: '', questionNumber: '1', note: '' };
    expect((await request.put(url, { headers, data: { ...fields, operationId: crypto.randomUUID(), expectedRevision: 1 } })).ok()).toBeTruthy();
    await page.goto(`${server.url}/admin/materials`);
    await page.getByLabel('家长账号').fill('parent'); await page.getByLabel('家长密码', { exact: true }).fill('family password 123');
    await page.getByRole('button', { name: '登录此设备', exact: true }).click();
    await page.getByLabel('家长密码', { exact: true }).fill('family password 123'); await page.getByRole('button', { name: '验证并进入管理', exact: true }).click();
    await page.getByRole('table', { name: '已收集资料' }).getByRole('button', { name: '打开', exact: true }).click();
    await page.getByLabel('备注（选填）').fill('已发送但丢失回执的编辑');
    let sent: Record<string, string> = {};
    await page.route(url, async route => { sent = route.request().headers(); await route.fetch(); await route.abort(); }, { times: 1 });
    await page.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('仍保留');
    expect((await request.put(url, { headers, data: { ...fields, operationId: crypto.randomUUID(), expectedRevision: 3, note: '回执丢失后另一设备的更新' } })).ok()).toBeTruthy();
    await page.getByLabel('备注（选填）').fill('本机继续编辑的内容');
    await expect(page.getByLabel('追加跨页图片', { exact: true })).toBeEnabled();
    await page.getByLabel('追加跨页图片', { exact: true }).setInputFiles({ name: '冲突中的追加页.png', mimeType: 'image/png', buffer: await sharp(bytes).flop().png().toBuffer() });
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    await page.getByRole('button', { name: '确认题目范围', exact: true }).click();
    await page.route(url, async route => { if (route.request().method() === 'GET') await route.abort(); else await route.continue(); });
    await page.getByRole('button', { name: '保存修改', exact: true }).click();
    const conflict = page.getByRole('region', { name: '处理保存冲突', exact: true });
    await expect(conflict.getByRole('alert')).toContainText('暂时无法读取当前版本');
    await expect(conflict.getByRole('button', { name: '保留本次编辑，继续核对', exact: true })).toBeDisabled();
    await expect(page.getByLabel('备注（选填）')).toHaveValue('本机继续编辑的内容');
    expect((await (await request.get(url, { headers })).json()).revision).toBe(4);
    await page.unroute(url);
    await request.delete(`${server.url}/api/v1/admin/grants`, { headers: { Authorization: sent.authorization!, 'X-Parent-Authorization': sent['x-parent-authorization']! } });
    await conflict.getByRole('button', { name: '重新读取当前版本', exact: true }).click();
    await expect(page.getByRole('heading', { name: '验证家长身份', exact: true })).toBeVisible();
    await page.getByLabel('家长密码', { exact: true }).fill('family password 123'); await page.getByRole('button', { name: '验证并进入管理', exact: true }).click();
    await expect(page.getByLabel('备注（选填）')).toHaveValue('本机继续编辑的内容');
    await conflict.getByRole('button', { name: '重新读取当前版本', exact: true }).click();
    await expect(conflict.getByRole('region', { name: '当前版本', exact: true })).toContainText('回执丢失后另一设备的更新');
    await expect(conflict.getByRole('region', { name: '本次编辑', exact: true })).toContainText('题目材料（2 个题目区）');
    await page.getByRole('button', { name: '返回列表', exact: true }).click();
    await expect(page.getByRole('dialog')).toBeVisible(); await page.getByRole('button', { name: '继续编辑', exact: true }).click();
    await page.setViewportSize({ width: 1440, height: 960 }); await page.screenshot({ path: 'test-results/admin-conflict-1440.png', fullPage: true });
    await conflict.getByRole('button', { name: '保留本次编辑，继续核对', exact: true }).click();
    await page.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('已同步到家庭资料库');
    const saved = await (await request.get(url, { headers })).json();
    expect(saved.revision).toBe(5); expect(saved.parts).toHaveLength(2); expect(saved.note).toBe('本机继续编辑的内容');
    await page.getByRole('button', { name: '返回列表', exact: true }).click();
    await page.getByRole('table', { name: '已收集资料' }).getByRole('button', { name: '打开', exact: true }).click();
    await expect(page.getByLabel('备注（选填）')).toHaveValue('本机继续编辑的内容');
    expect((await (await request.get(`${server.url}/api/v1/collection/questions?state=collected`, { headers })).json()).total).toBe(1);
  } finally { await server.stop(); await rm(dir, { recursive: true, force: true }); }
});

test('共享原文和答案冲突可核对材料并选择版本，处理后的保存响应丢失可重试且关联正确', async ({ page, request }) => {
  const dir = await mkdtemp(join(tmpdir(), 'klbook-material-conflict-'));
  const server = await startServer(dir);
  try {
    const setupCode = (await readFile(join(dir, 'setup-code.txt'), 'utf8')).trim();
    const first = await (await request.post(`${server.url}/api/v1/setup`, { data: { setupCode, username: 'parent', password: 'family password 123', learnerName: '小明', deviceName: '另一设备' } })).json();
    const headers = { Authorization: `Bearer ${first.token}` };
    const bytes = await sharp(await readFile('test/fixtures/paper.svg')).png().toBuffer();
    const draft = await (await request.post(`${server.url}/api/v1/collection/drafts`, { headers: { ...headers, 'Content-Type': 'image/png', 'Idempotency-Key': crypto.randomUUID() }, data: bytes })).json();
    const region = { x: 0, y: 0, width: 1, height: 1 };
    const readingId = crypto.randomUUID(), readingUrl = `${server.url}/api/v1/collection/reading-materials/${readingId}`;
    const reading = { operationId: crypto.randomUUID(), expectedRevision: 0, title: '阅读原文', parts: [{ id: crypto.randomUUID(), pageId: draft.originalPage.id, region }] };
    expect((await request.put(readingUrl, { headers, data: reading })).ok()).toBeTruthy();
    const url = `${server.url}/api/v1/collection/questions/${draft.id}`;
    expect((await request.put(url, { headers, data: { operationId: crypto.randomUUID(), expectedRevision: 1, state: 'collected', subjectId: 'chinese', region, sourceId: null, pageNumber: '', questionNumber: '1', note: '', readingMaterialId: readingId } })).ok()).toBeTruthy();
    await page.goto(`${server.url}/learn`);
    await page.getByLabel('家长账号').fill('parent'); await page.getByLabel('家长密码', { exact: true }).fill('family password 123');
    await page.getByRole('button', { name: '登录此设备', exact: true }).click();
    await page.getByRole('button', { name: '打开错题', exact: true }).click();
    await page.getByRole('button', { name: '补充或更正信息', exact: true }).click();
    await page.getByRole('button', { name: '编辑已关联原文', exact: true }).click();
    await page.getByLabel('阅读材料名称').fill('本次修改的原文');
    expect((await request.put(readingUrl, { headers, data: { ...reading, operationId: crypto.randomUUID(), expectedRevision: 1, title: '其他设备更正的原文' } })).ok()).toBeTruthy();
    await page.getByRole('button', { name: '保存并返回题目', exact: true }).click();
    const conflict = page.getByRole('region', { name: '处理保存冲突', exact: true });
    await expect(conflict.getByRole('region', { name: '当前版本', exact: true })).toContainText('其他设备更正的原文');
    await expect(conflict.getByRole('region', { name: '本次编辑', exact: true })).toContainText('本次修改的原文');
    await conflict.getByRole('button', { name: '放弃本次编辑，采用当前版本', exact: true }).click();
    await expect(page.getByLabel('阅读材料名称')).toHaveValue('其他设备更正的原文');
    await page.getByLabel('阅读材料名称').fill('双方核对后的原文');
    await page.getByRole('button', { name: '保存并返回题目', exact: true }).click();
    await page.getByRole('button', { name: '补充纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '从本题原始页 1 框选', exact: true }).click();
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    const remoteParts = [{ id: crypto.randomUUID(), pageId: draft.originalPage.id, region: { x: .2, y: .2, width: .5, height: .5 } }];
    expect((await request.put(`${url}/answers`, { headers, data: { operationId: crypto.randomUUID(), expectedRevision: 2, parts: remoteParts } })).ok()).toBeTruthy();
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(conflict).toBeVisible();
    for (const version of ['当前版本', '本次编辑']) {
      await conflict.getByRole('region', { name: version, exact: true }).getByText('纸质答案（1 个解答区）', { exact: true }).click();
      await expect(conflict.getByRole('region', { name: version, exact: true }).getByRole('img', { name: '纸质解答区', exact: true })).toBeVisible();
    }
    await conflict.getByRole('button', { name: '保留本次编辑，继续核对', exact: true }).click();
    await page.route('**/api/v1/collection/questions/*/answers', async route => { if (route.request().method() === 'PUT') { await route.fetch(); await route.abort(); } else await route.continue(); }, { times: 1 });
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('仍保留');
    await page.getByRole('button', { name: '保存答案并返回', exact: true }).click();
    await expect(page.getByRole('heading', { name: '补充或更正信息', exact: true })).toBeVisible();
    const saved = await (await request.get(url, { headers })).json();
    expect(saved.revision).toBe(4); expect(saved.answerParts).toHaveLength(1); expect(saved.answerParts[0].region).toEqual(region);
    expect(saved.readingMaterial.title).toBe('双方核对后的原文'); expect(saved.readingMaterial.revision).toBe(3);
    expect(saved.parts).toHaveLength(1);
    await page.getByRole('button', { name: '从原始页新建阅读材料', exact: true }).click();
    await page.getByLabel('阅读材料名称').fill('新建但还没关联的原文');
    await page.getByRole('button', { name: '选择整页', exact: true }).click();
    expect((await request.put(url, { headers, data: { operationId: crypto.randomUUID(), expectedRevision: 4, state: 'collected', subjectId: 'chinese', region, sourceId: null, pageNumber: '', questionNumber: '1', note: '关联原文期间另一设备补的备注' } })).ok()).toBeTruthy();
    await page.getByRole('button', { name: '保存并返回题目', exact: true }).click();
    await expect(page.getByText('原文已保存，关联题目时发生冲突。', { exact: true })).toBeVisible();
    await expect(conflict.getByRole('region', { name: '当前版本', exact: true })).toContainText('关联原文期间另一设备补的备注');
    await conflict.getByRole('button', { name: '保留本次编辑，继续核对', exact: true }).click();
    await expect(page.getByLabel('备注（选填）')).toHaveValue('关联原文期间另一设备补的备注');
    await page.getByRole('button', { name: '整理纸质答案', exact: true }).click();
    await page.getByRole('button', { name: '放弃本次修改并离开', exact: true }).click();
    await page.getByRole('button', { name: '返回题目', exact: true }).click();
    await expect(page.getByRole('combobox', { name: '阅读材料（选填）', exact: true })).toHaveValue(readingId);
    await page.getByRole('combobox', { name: '阅读材料（选填）', exact: true }).selectOption({ label: '新建但还没关联的原文 · 1 个原文区' });
    await page.getByRole('button', { name: '保存修改', exact: true }).click();
    await expect(page.getByRole('heading', { name: '错题详情', exact: true })).toBeVisible();
    const linked = await (await request.get(url, { headers })).json();
    expect(linked.revision).toBe(6); expect(linked.note).toBe('关联原文期间另一设备补的备注');
    expect(linked.readingMaterial.title).toBe('新建但还没关联的原文'); expect(linked.answerParts).toEqual(saved.answerParts);
    expect((await (await request.get(`${server.url}/api/v1/collection/reading-materials`, { headers })).json()).total).toBe(2);
  } finally { await server.stop(); await rm(dir, { recursive: true, force: true }); }
});
